name: ml
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - jupyter_contrib_nbextensions
  - requests
  # - librosa
  - pip:
    - nest_asyncio
    - redis
    - redisearch