name: ml
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>=3.8
  - jupyter_contrib_nbextensions
  - pip
  - requests
  - yaml
  - fire
  - schedule
  - aiohttp
  - pandas
  - pyarrow
  - librosa
  - scikit-learn
  - redisearch
  - pip:
    - twilio
    - sendgrid