name: ml
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - requests
  - jupyter_contrib_nbextensions
  - pyarrow
  - pandas
  - matplotlib
  - scikit-learn
  - librosa
  - pip:
    - nest_asyncio
    - redis
    - redisearch