name: ml
channels:
  - anaconda
  - conda-forge
dependencies:
  - pip
  - requests
  - pyarrow=3.0.0
  - feather-format
  # - pandas=1.2.4
  - jupyter_contrib_nbextensions
  - matplotlib
  - seaborn
  - scikit-learn
  - librosa
  - pip:
    - nest_asyncio
    - redis
    - redisearch