name: ml
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>=3.8
  - jupyter_contrib_nbextensions
  - pip
  - requests
  - yaml
  - fire
  - schedule
  - aiohttp
  - librosa
  - pip:
    - twilio
    - sendgrid