name: ml
channels:
  - anaconda
  - conda-forge
dependencies:
  - pip
  - requests
  - jupyter_contrib_nbextensions
  - pyarrow
  - pandas=1.2.4
  - matplotlib
  - scikit-learn
  - librosa
  - pip:
    - nest_asyncio
    - redis
    - redisearch